// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MONSTER_H_
#define FLATBUFFERS_GENERATED_MONSTER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct Monster;
struct MonsterBuilder;

struct Monster FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MonsterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_HEALTH = 6,
    VT_MP = 8,
    VT_EXP = 10,
    VT_GOLD = 12,
    VT_LEVEL = 14,
    VT_WEAPON = 16
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t health() const {
    return GetField<int32_t>(VT_HEALTH, 0);
  }
  int32_t mp() const {
    return GetField<int32_t>(VT_MP, 0);
  }
  int32_t exp() const {
    return GetField<int32_t>(VT_EXP, 0);
  }
  int32_t gold() const {
    return GetField<int32_t>(VT_GOLD, 0);
  }
  int32_t level() const {
    return GetField<int32_t>(VT_LEVEL, 0);
  }
  const ::flatbuffers::String *weapon() const {
    return GetPointer<const ::flatbuffers::String *>(VT_WEAPON);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_HEALTH, 4) &&
           VerifyField<int32_t>(verifier, VT_MP, 4) &&
           VerifyField<int32_t>(verifier, VT_EXP, 4) &&
           VerifyField<int32_t>(verifier, VT_GOLD, 4) &&
           VerifyField<int32_t>(verifier, VT_LEVEL, 4) &&
           VerifyOffset(verifier, VT_WEAPON) &&
           verifier.VerifyString(weapon()) &&
           verifier.EndTable();
  }
};

struct MonsterBuilder {
  typedef Monster Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Monster::VT_NAME, name);
  }
  void add_health(int32_t health) {
    fbb_.AddElement<int32_t>(Monster::VT_HEALTH, health, 0);
  }
  void add_mp(int32_t mp) {
    fbb_.AddElement<int32_t>(Monster::VT_MP, mp, 0);
  }
  void add_exp(int32_t exp) {
    fbb_.AddElement<int32_t>(Monster::VT_EXP, exp, 0);
  }
  void add_gold(int32_t gold) {
    fbb_.AddElement<int32_t>(Monster::VT_GOLD, gold, 0);
  }
  void add_level(int32_t level) {
    fbb_.AddElement<int32_t>(Monster::VT_LEVEL, level, 0);
  }
  void add_weapon(::flatbuffers::Offset<::flatbuffers::String> weapon) {
    fbb_.AddOffset(Monster::VT_WEAPON, weapon);
  }
  explicit MonsterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Monster> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Monster>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Monster> CreateMonster(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t health = 0,
    int32_t mp = 0,
    int32_t exp = 0,
    int32_t gold = 0,
    int32_t level = 0,
    ::flatbuffers::Offset<::flatbuffers::String> weapon = 0) {
  MonsterBuilder builder_(_fbb);
  builder_.add_weapon(weapon);
  builder_.add_level(level);
  builder_.add_gold(gold);
  builder_.add_exp(exp);
  builder_.add_mp(mp);
  builder_.add_health(health);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Monster> CreateMonsterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t health = 0,
    int32_t mp = 0,
    int32_t exp = 0,
    int32_t gold = 0,
    int32_t level = 0,
    const char *weapon = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto weapon__ = weapon ? _fbb.CreateString(weapon) : 0;
  return CreateMonster(
      _fbb,
      name__,
      health,
      mp,
      exp,
      gold,
      level,
      weapon__);
}

inline const Monster *GetMonster(const void *buf) {
  return ::flatbuffers::GetRoot<Monster>(buf);
}

inline const Monster *GetSizePrefixedMonster(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Monster>(buf);
}

template <bool B = false>
inline bool VerifyMonsterBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Monster>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMonsterBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Monster>(nullptr);
}

inline void FinishMonsterBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Monster> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMonsterBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Monster> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_MONSTER_H_
